name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install-dependencies
        run: >
          sudo pip3 install conan &&
          sudo apt-get install -yq gcc-11 g++-11
      - name: create-build-dir
        run: mkdir build
      - name: conan-install
        run: >
          cd build &&
          conan install
          -s build_type=Debug
          -s compiler=gcc
          -s compiler.version=11
          -s compiler.libcxx=libstdc++11
          -e CC=gcc-11
          -e CXX=g++-11
          --build missing
          ..
      - name: conan-build
        run: >
          cd build &&
          conan build ..
      - name: conan-test
        run: >
          cd build &&
          conan build .. --test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
