name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install-dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -yq ${{ matrix.DEPS }}
      - name: conan-install
        run: >
          cd build &&
          conand install .. --build missing
      - name: cmake-configure
        run: >
          cd build &&
          cmake .. -DCMAKE_BUILD_TYPE=Debug
      - name: cmake-build
        run: cmake --build build
      - name: test-run
        run: cmake --build build --target test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
